language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t morciu/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true morciu/react-test npm test

after_success:
  - docker build -t morciu/multi-client ./client
  - docker build -t morciu/multi-nginx ./nginx
  - docker build -t morciu/multi-server ./server
  - docker build -t morciu/multi-worker ./worker